sudo: required

language: go

services:
  - docker

before_install:
  - docker build -t copernet/copernicus .

script:
  - docker run copernet/copernicus $GOPATH/src/github.com/copernet/copernicus/ci.sh $COVERALLS_TOKEN
