sudo: required

language: go

services:
  - docker

before_install:
  - docker build -t copernet/copernicus .

script:
  - docker run copernet/copernicus /go/src/github.com/copernet/copernicus/check.sh
  - docker run copernet/copernicus ls /go/src/github.com/copernet/copernicus
  - docker run copernet/copernicus ls /go/bin
  - docker run copernet/copernicus /go/bin/goveralls -h
  - docker run copernet/copernicus /go/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN 
