sudo: required

language: go

services:
  - docker

before_install:
  - docker build -t copernet/copernicus .

script:
  - docker run copernet/copernicus /go/src/github.com/copernet/copernicus/ci.sh $COVERALLS_TOKEN

notifications:
  email:
    on_success: change
    on_failure: alwayss
