sudo: required

language: go

services:
  - docker

before_install:
  - docker build -t copernet/copernicus .
  - docker run -d --name copernicus
script:
  - docker exec copernicus -e TRAVIS_JOB_ID="$TRAVIS_JOB_ID" -e TRAVIS_BRANCH="$TRAVIS_BRANCH"
  - docker exec copernicus /go/src/github.com/copernet/copernicus/ci.sh $COVERALLS_TOKEN
