sudo: required

language: go

services:
  - docker

before_install:
  - docker build -t copernet/copernicus .
  - docker run -it -d --name copernicus -e TRAVIS_JOB_ID="$TRAVIS_JOB_ID" -e TRAVIS_BRANCH="$TRAVIS_BRANCH" copernet/copernicus
script:
  - docker exec copernicus /go/src/github.com/copernet/copernicus/check.sh
  - docker exec copernicus goveralls -coverprofile=/go/src/github.com/coperrnet/copernicus/coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
  - docker exec copernicus pipenv run python /walle/example_test.py

notifications:
  email:
    on_success: change
    on_failure: alwayss
